### ISSUE TITLE
Gnome 40 and Gtk-4.0 Support

### ISSUE THREAD

**Issue by Dunemask** [darkomarko42/Venta-X#2]
As Gnome and GTK versions have matured throughout the last year, would it be possible for you to update this theme to the new standards? I've looked into doing it myself, but i'm not familiar enough with GTK styling to do much unfortunately. 

This is the best theme I have ever seen, and i'm so glad i've been able to use it the last few months!

**Comment by darkomarko42** [comment]
yes im gonna update all my themes :) now im working on marwaita, after that will update all these themes with all the fixes and improvements of marwaita :)
